#include "../include/all.hpp"

#include <cstdint>

instruction instructions[0x100] = {
    // 0x0X
    [0x00] = {.type = IN_NOP, .mode = AM_IMP},
    [0x01] = {.type = IN_LD, .mode = AM_R_D16, .reg1 = RT_BC},
    [0x02] = {.type = IN_LD, .mode = AM_MR_R, .reg1 = RT_BC, .reg2 = RT_A},
    [0x03] = {.type = IN_INC, .mode = AM_R, .reg1 = RT_BC},
    [0x04] = {.type = IN_INC, .mode = AM_R, .reg1 = RT_B},
    [0x05] = {.type = IN_DEC, .mode = AM_R, .reg1 = RT_B},
    [0x06] = {.type = IN_LD, .mode = AM_R_D8, .reg1=RT_B},
    [0x07] = {.type = IN_RLCA},
    [0x08] = {.type = IN_LD, .mode = AM_A16_R, RT_NONE, RT_SP},
    [0x09] = {.type = IN_ADD, .mode = AM_R_R, RT_HL, RT_BC},
    [0x0A] = {.type = IN_LD, .mode = AM_R_MR, RT_A, RT_BC},
    [0x0B] = {.type = IN_DEC, .mode = AM_R, RT_BC},
    [0x0C] = {.type = IN_INC, .mode = AM_R, RT_C},
    [0x0D] = {.type = IN_DEC, .mode = AM_R, RT_C},
    [0x0E] = {.type = IN_LD, .mode = AM_R_D8, RT_C},
    [0x0F] = {.type = IN_RRCA},

    // 0x1X
    [0x10] = {.type = IN_STOP},
    [0x11] = {.type = IN_LD, .mode = AM_R_D16, RT_DE},
    [0x12] = {.type = IN_LD, .mode = AM_MR_R, RT_DE, RT_A},
    [0x13] = {.type = IN_INC, .mode = AM_R, RT_DE},
    [0x14] = {.type = IN_INC, .mode = AM_R, RT_D},
    [0x15] = {.type = IN_DEC, .mode = AM_R, RT_D},
    [0x16] = {.type = IN_LD, .mode = AM_R_D8, RT_D},
    [0x17] = {.type = IN_RLA},
    [0x18] = {.type = IN_JR, .mode = AM_D8},
    [0x19] = {.type = IN_ADD, .mode = AM_R_R, RT_HL, RT_DE},
    [0x1A] = {.type = IN_LD, .mode = AM_R_MR, RT_A, RT_DE},
    [0x1B] = {.type = IN_DEC, .mode = AM_R, RT_DE},
    [0x1C] = {.type = IN_INC, .mode = AM_R, RT_E},
    [0x1D] = {.type = IN_DEC, .mode = AM_R, RT_E},
    [0x1E] = {.type = IN_LD, .mode = AM_R_D8, RT_E},
    [0x1F] = {.type = IN_RRA},/*  */

    // 0x2X
    [0x20] = {.type = IN_JR, .mode = AM_D8, RT_NONE, RT_NONE, .cond = CT_NZ},
    [0x21] = {.type = IN_LD, .mode = AM_R_D16, RT_HL},
    [0x22] = {.type = IN_LD, .mode = AM_HLI_R, RT_HL, RT_A},
    [0x23] = {.type = IN_INC, .mode = AM_R, RT_HL},
    [0x24] = {.type = IN_INC, .mode = AM_R, RT_H},
    [0x25] = {.type = IN_DEC, .mode = AM_R, RT_H},
    [0x26] = {.type = IN_LD, .mode = AM_R_D8, RT_H},
    [0x27] = {.type = IN_DAA},
    [0x28] = {.type = IN_JR, .mode = AM_D8, RT_NONE, RT_NONE, .cond = CT_Z},
    [0x29] = {.type = IN_ADD, .mode = AM_R_R, RT_HL, RT_HL},
    [0x2A] = {.type = IN_LD, .mode = AM_R_HLI, RT_A, RT_HL},
    [0x2B] = {.type = IN_DEC, .mode = AM_R, RT_HL},
    [0x2C] = {.type = IN_INC, .mode = AM_R, RT_L},
    [0x2D] = {.type = IN_DEC, .mode = AM_R, RT_L},
    [0x2E] = {.type = IN_LD, .mode = AM_R_D8, RT_L},
    [0x2F] = {.type = IN_CPL},
    // 0x3X
    [0x30] = {.type = IN_JR, .mode = AM_D8, RT_NONE, RT_NONE, .cond = CT_NC},
    [0x31] = {.type = IN_LD, .mode = AM_R_D16, RT_SP},
    [0x32] = {.type = IN_LD, .mode = AM_HLD_R, RT_HL, RT_A},
    [0x33] = {.type = IN_INC, .mode = AM_R, RT_SP},
    [0x34] = {.type = IN_INC, .mode = AM_MR, RT_HL},
    [0x35] = {.type = IN_DEC, .mode = AM_MR, RT_HL},
    [0x36] = {.type = IN_LD, .mode = AM_MR_D8, RT_HL},
    [0x37] = {.type = IN_SCF},
    [0x38] = {.type = IN_JR, .mode = AM_D8, RT_NONE, RT_NONE, .cond = CT_C},
    [0x39] = {.type = IN_ADD, .mode = AM_R_R, RT_HL, RT_SP},
    [0x3A] = {.type = IN_LD, .mode = AM_R_HLD, RT_A, RT_HL},
    [0x3B] = {.type = IN_DEC, .mode = AM_R, RT_SP},
    [0x3C] = {.type = IN_INC, .mode = AM_R, RT_A},
    [0x3D] = {.type = IN_DEC, .mode = AM_R, RT_A},
    [0x3E] = {.type = IN_LD, .mode = AM_R_D8, RT_A},
    [0x3F] = {.type = IN_CCF},
    // 0x4X
    [0x40] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_B},
    [0x41] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_C},
    [0x42] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_D},
    [0x43] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_E},
    [0x44] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_H},
    [0x45] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_L},
    [0x46] = {.type = IN_LD, .mode = AM_R_MR, RT_B, RT_HL},
    [0x47] = {.type = IN_LD, .mode = AM_R_R, RT_B, RT_A},
    [0x48] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_B},
    [0x49] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_C},
    [0x4A] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_D},
    [0x4B] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_E},
    [0x4C] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_H},
    [0x4D] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_L},
    [0x4E] = {.type = IN_LD, .mode = AM_R_MR, RT_C, RT_HL},
    [0x4F] = {.type = IN_LD, .mode = AM_R_R, RT_C, RT_A},

    // 0x5X
    [0x50] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_B},
    [0x51] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_C},
    [0x52] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_D},
    [0x53] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_E},
    [0x54] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_H},
    [0x55] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_L},
    [0x56] = {.type = IN_LD, .mode = AM_R_MR, RT_D, RT_HL},
    [0x57] = {.type = IN_LD, .mode = AM_R_R, RT_D, RT_A},
    [0x58] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_B},
    [0x59] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_C},
    [0x5A] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_D},
    [0x5B] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_E},
    [0x5C] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_H},
    [0x5D] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_L},
    [0x5E] = {.type = IN_LD, .mode = AM_R_MR, RT_E, RT_HL},
    [0x5F] = {.type = IN_LD, .mode = AM_R_R, RT_E, RT_A},

    // 0x6X
    [0x60] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_B},
    [0x61] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_C},
    [0x62] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_D},
    [0x63] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_E},
    [0x64] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_H},
    [0x65] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_L},
    [0x66] = {.type = IN_LD, .mode = AM_R_MR, RT_H, RT_HL},
    [0x67] = {.type = IN_LD, .mode = AM_R_R, RT_H, RT_A},
    [0x68] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_B},
    [0x69] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_C},
    [0x6A] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_D},
    [0x6B] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_E},
    [0x6C] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_H},
    [0x6D] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_L},
    [0x6E] = {.type = IN_LD, .mode = AM_R_MR, RT_L, RT_HL},
    [0x6F] = {.type = IN_LD, .mode = AM_R_R, RT_L, RT_A},

    // 0x7X
    [0x70] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_B},
    [0x71] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_C},
    [0x72] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_D},
    [0x73] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_E},
    [0x74] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_H},
    [0x75] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_L},
    [0x76] = {.type = IN_HALT},
    [0x77] = {.type = IN_LD, .mode = AM_MR_R, RT_HL, RT_A},
    [0x78] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_B},
    [0x79] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_C},
    [0x7A] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_D},
    [0x7B] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_E},
    [0x7C] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_H},
    [0x7D] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_L},
    [0x7E] = {.type = IN_LD, .mode = AM_R_MR, RT_A, RT_HL},
    [0x7F] = {.type = IN_LD, .mode = AM_R_R, RT_A, RT_A},

    // 0x8X
    [0x80] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_B},
    [0x81] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_C},
    [0x82] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_D},
    [0x83] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_E},
    [0x84] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_H},
    [0x85] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_L},
    [0x86] = {.type = IN_ADD, .mode = AM_R_MR, RT_A, RT_HL},
    [0x87] = {.type = IN_ADD, .mode = AM_R_R, RT_A, RT_A},
    [0x88] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_B},
    [0x89] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_C},
    [0x8A] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_D},
    [0x8B] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_E},
    [0x8C] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_H},
    [0x8D] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_L},
    [0x8E] = {.type = IN_ADC, .mode = AM_R_MR, RT_A, RT_HL},
    [0x8F] = {.type = IN_ADC, .mode = AM_R_R, RT_A, RT_A},

    // 0x9X
    [0x90] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_B},
    [0x91] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_C},
    [0x92] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_D},
    [0x93] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_E},
    [0x94] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_H},
    [0x95] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_L},
    [0x96] = {.type = IN_SUB, .mode = AM_R_MR, RT_A, RT_HL},
    [0x97] = {.type = IN_SUB, .mode = AM_R_R, RT_A, RT_A},
    [0x98] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_B},
    [0x99] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_C},
    [0x9A] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_D},
    [0x9B] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_E},
    [0x9C] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_H},
    [0x9D] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_L},
    [0x9E] = {.type = IN_SBC, .mode = AM_R_MR, RT_A, RT_HL},
    [0x9F] = {.type = IN_SBC, .mode = AM_R_R, RT_A, RT_A},

    // 0xAX
    [0xA0] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_B},
    [0xA1] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_C},
    [0xA2] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_D},
    [0xA3] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_E},
    [0xA4] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_H},
    [0xA5] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_L},
    [0xA6] = {.type = IN_AND, .mode = AM_R_MR, RT_A, RT_HL},
    [0xA7] = {.type = IN_AND, .mode = AM_R_R, RT_A, RT_A},
    [0xA8] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_B},
    [0xA9] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_C},
    [0xAA] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_D},
    [0xAB] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_E},
    [0xAC] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_H},
    [0xAD] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_L},
    [0xAE] = {.type = IN_XOR, .mode = AM_R_MR, RT_A, RT_HL},
    [0xAF] = {.type = IN_XOR, .mode = AM_R_R, RT_A, RT_A},

    [0xB0] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_B},
    [0xB1] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_C},
    [0xB2] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_D},
    [0xB3] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_E},
    [0xB4] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_H},
    [0xB5] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_L},
    [0xB6] = {.type = IN_OR, .mode = AM_R_MR, RT_A, RT_HL},
    [0xB7] = {.type = IN_OR, .mode = AM_R_R, RT_A, RT_A},
    [0xB8] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_B},
    [0xB9] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_C},
    [0xBA] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_D},
    [0xBB] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_E},
    [0xBC] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_H},
    [0xBD] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_L},
    [0xBE] = {.type = IN_CP, .mode = AM_R_MR, RT_A, RT_HL},
    [0xBF] = {.type = IN_CP, .mode = AM_R_R, RT_A, RT_A},

    [0xC0] = {.type = IN_RET, .mode = AM_IMP, RT_NONE, RT_NONE, .cond = CT_NZ},
    [0xC1] = {.type = IN_POP, .mode = AM_R, RT_BC},
    [0xC2] = {.type = IN_JP, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_NZ},
    [0xC3] = {.type = IN_JP, .mode = AM_D16},
    [0xC4] = {.type = IN_CALL, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_NZ},
    [0xC5] = {.type = IN_PUSH, .mode = AM_R, RT_BC},
    [0xC6] = {.type = IN_ADD, .mode = AM_R_D8, RT_A},
    [0xC7] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              0x00},
    [0xC8] = {.type = IN_RET, .mode = AM_IMP, RT_NONE, RT_NONE, .cond = CT_Z},
    [0xC9] = {.type = IN_RET},
    [0xCA] = {.type = IN_JP, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_Z},
    [0xCB] = {.type = IN_CB, .mode = AM_D8},
    [0xCC] = {.type = IN_CALL, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_Z},
    [0xCD] = {.type = IN_CALL, .mode = AM_D16},
    [0xCE] = {.type = IN_ADC, .mode = AM_R_D8, RT_A},
    [0xCF] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              0x08},

    [0xD0] = {.type = IN_RET, .mode = AM_IMP, RT_NONE, RT_NONE, .cond = CT_NC},
    [0xD1] = {.type = IN_POP, .mode = AM_R, RT_DE},
    [0xD2] = {.type = IN_JP, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_NC},
    [0xD4] = {.type = IN_CALL, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_NC},
    [0xD5] = {.type = IN_PUSH, .mode = AM_R, RT_DE},
    [0xD6] = {.type = IN_SUB, .mode = AM_R_D8, .reg1 = RT_A},
    [0xD7] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              0x10},
    [0xD8] = {.type = IN_RET, .mode = AM_IMP, RT_NONE, RT_NONE, .cond = CT_C},
    [0xD9] = {.type = IN_RETI},
    [0xDA] = {.type = IN_JP, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_C},
    [0xDC] = {.type = IN_CALL, .mode = AM_D16, RT_NONE, RT_NONE, .cond = CT_C},
    [0xDE] = {.type = IN_SBC, .mode = AM_R_D8, .reg1 = RT_A},
    [0xDF] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              0x18},

    // 0xEX
    [0xE0] = {.type = IN_LDH, .mode = AM_A8_R, RT_NONE, RT_A},
    [0xE1] = {.type = IN_POP, .mode = AM_R, RT_HL},
    [0xE2] = {.type = IN_LD, .mode = AM_MR_R, RT_C, RT_A},
    [0xE5] = {.type = IN_PUSH, .mode = AM_R, RT_HL},
    [0xE6] = {.type = IN_AND, .mode = AM_R_D8, .reg1 = RT_A},
    [0xE7] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              .param = 0x20},
    [0xE8] = {.type = IN_ADD, .mode = AM_R_D8, RT_SP},
    [0xE9] = {.type = IN_JP, .mode = AM_R, RT_HL},

    [0xEA] = {.type = IN_LD, .mode = AM_A16_R, RT_NONE, RT_A},
    [0xEE] = {.type = IN_XOR, .mode = AM_R_D8, .reg1 = RT_A},
    [0xEF] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              .param = 0x28},

    // 0xFX
    [0xF0] = {.type = IN_LDH, .mode = AM_R_A8, RT_A},
    [0xF1] = {.type = IN_POP, .mode = AM_R, RT_AF},
    [0xF2] = {.type = IN_LD, .mode = AM_R_MR, RT_A, RT_C},
    [0xF3] = {.type = IN_DI},
    [0xF5] = {.type = IN_PUSH, .mode = AM_R, RT_AF},
    [0xF6] = {.type = IN_OR, .mode = AM_R_D8, .reg1 = RT_A},
    [0xF7] = {.type = IN_RST,
              .mode = AM_IMP,
              RT_NONE,
              RT_NONE,
              .cond = CT_NONE,
              .param = 0x30},
    [0xF8] = {.type = IN_LD, .mode = AM_HL_SPR, .reg1 = RT_HL, .reg2 = RT_SP},
    [0xF9] = {.type = IN_LD, .mode = AM_R_R, .reg1 = RT_SP, .reg2 = RT_HL},
    [0xFA] = {.type = IN_LD, .mode = AM_R_A16, RT_A},
    [0xFB] = {.type = IN_EI},
    [0xFE] = {.type = IN_CP, .mode = AM_R_D8, .reg1 = RT_A},
    [0xFF] = {.type = IN_RST,
              .mode = AM_IMP,
              .reg1 = RT_NONE,
              .reg2 = RT_NONE,
              .cond = CT_NONE,
              .param = 0x38},

};

const std::string inst_lookup[] = {
    "<NONE>", "NOP",     "LD",     "INC",    "DEC",    "RLCA",  "ADD",
    "RRCA",   "STOP",    "RLA",    "JR",     "RRA",    "DAA",   "CPL",
    "SCF",    "CCF",     "HALT",   "ADC",    "SUB",    "SBC",   "AND",
    "XOR",    "OR",      "CP",     "POP",    "JP",     "PUSH",  "RET",
    "CB",     "CALL",    "RETI",   "LDH",    "JPHL",   "DI",    "EI",
    "RST",    "IN_ERR",  "IN_RLC", "IN_RRC", "IN_RL",  "IN_RR", "IN_SLA",
    "IN_SRA", "IN_SWAP", "IN_SRL", "IN_BIT", "IN_RES", "IN_SET"};

const std::string reg_lookup[]{
    "RT_NONE", "RT_A",  "RT_F",  "RT_B",  "RT_C",  "RT_D",  "RT_E",  "RT_H",
    "RT_L",    "RT_SP", "RT_PC", "RT_AF", "RT_BC", "RT_DE", "RT_HL",
};

const std::string &get_reg_name(reg_type reg) { return reg_lookup[reg]; }

const std::string &get_inst_name(in_type type) { return inst_lookup[type]; }

const std::string inst_toString(cpu_context *ctx) {
  instruction *cur_instruction = ctx->cur_instruction;
  auto ret = fmt::format("Instruction 0x{:X} = (type=\"{}\", "
                         "reg1=\"{}\", reg2=\"{}\")",
                         ctx->op_code, get_inst_name(cur_instruction->type),
                         get_reg_name(cur_instruction->reg1),
                         get_reg_name(cur_instruction->reg2));
  return ret;
}

instruction *get_instruction_by_opcode(uint8_t opcode) {
  if (instructions[opcode].type == IN_NONE) {
    return nullptr;
  }
  return &instructions[opcode];
}
